services:
  siav-api:
    build: .
    container_name: siav-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:8080"
    env_file:
      - ./.env
    networks:
      - internal-net
      - frontend-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  siav-zipkin:
    image: openzipkin/zipkin
    container_name: siav-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  internal-net:
    external: true
  frontend-net:
    external: true